[config]
schemaVersion = "0.0.1"


[package]
namespace = "JarlUlsfark"
name = "Horde_Mode"
versionNumber = "0.0.1"
description = "Adds A Horde Mode to Dream Dives. (Rift of Thessaly not implemented, prefer to avoid)"
websiteUrl = "https://github.com/Tal-lev/Horde_Mode"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"
NikkelM-Zagreus_Journey = "1.2.0"
zerp-BossRush = "0.3.2"

# Uncomment the section to add any soft dependecies.
# Learn more about them here https://sgg-modding.github.io/Hades2ModWiki/docs/creating-mods/first-mod-guide/mod-template#packagerom_soft_deps
# [package.rom_soft_deps]
# AuthorName-ModName = "0.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Uncomment (remove the #) the three lines below if you have any files to copy to the plugins_data folder (like custom .pkg files)
[[build.copy]]
source = "./data"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
